### ISSUE TITLE
Can this be enhanced to function with the S4 Monitor?

### ISSUE THREAD

**Issue by duenni** [andresol/waterrower-a1-logger#11]
Hi,

this project looks really cool!
Will this only work with the A1 logger or can this be enhanced to function with an S4 Monitor also?
Keep up the good work!

Greets

**Comment by andresol** [comment]
This project only works for A1, but it could easy work on a S4 Monitor also. The S4 Monitor has USB support and that should make it easy to get data. I only have the A1 and that makes it impossible for me to develop it for the S4 Monitor.
